version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8020:8080

  mongo:
    image: mongo:3.6
    # restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    # networks:
    #   - backend

  mongo-express:
    image: mongo-express
    # restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    links: 
      - mongo:mongo
    # networks:
    #   - backend
  
  redis:
    image: redis:6.2
    # restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    # networks:
    #   - backend
  
  api: 
    container_name: api
    build: ./api
    ports :
      - 8080:8080
    # networks:
    #   - backend
    environment:
      PGUSER: postgres
      PGHOST: db
      PGPASSWORD: example
      PGDATABASE: testing
      PGPORT: 5432
    links:
      - mongo:database
      - redis:queue
      - db:db

  logger:
    tty: true
    container_name: logger
    build:
      context: ./pythonJobs
      dockerfile: ./Dockerfile_Logger
    links:
      - mongo:database
      - redis:queue
  
  attacker:
    tty: true
    container_name: attacker
    build:
      context: ./pythonJobs
      dockerfile: ./Dockerfile_Attacker
    links:
      - redis:queue