version: '3.1'

services:

  mongo:
    image: mongo:3.6
    # restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    # networks:
    #   - backend

  mongo-express:
    image: mongo-express
    # restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    # networks:
    #   - backend
  
  redis:
    image: redis:6.2
    # restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    # networks:
    #   - backend
  
  api: 
    container_name: api
    build: ./api
    ports :
      - 8080:8080
    # networks:
    #   - backend
    links:
      - mongo:database
      - redis:queue

# networks:
#   backend: 
#     driver: bridge
  

  # process-jobs:
  #   tty: true
  #   container_name: process-jobs
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile